<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="content-type" content="text/html; charset=utf-8"/>
    <title>Thank you for registering!</title>
    <style>
        h1 {
            color: cadetblue;
        }

        h2 {
            color: red;
        }
    </style>
</head>
<body>
<h1>Registration link:</h1>
<h2><a href="${server_url}/confirm/${confirm_code}">Follow the link</a></h2>
</body>
</html>
