<#ftl encoding="UTF-8"/>
<#import "parts/base.ftlh" as p/>
<@p.page>

    <title>Registration successful</title>

    <div class="main_container">
        <h1 style="text-align:center;">You have successfully registered!</h1>
        <h2 style="text-align:center;">
            <button type="submit" class="btn btn-link"><span> <a
                            href="/login">Click to go to sign in</a></span></button>
        </h2>
    </div>

</@p.page>